### ISSUE TITLE
Tutorials master ticket

### ISSUE THREAD

**Issue by Ishadijcks** [project-march/tutorials#22]
An overview of all tutorials we still need to write before we can consider them to be done. Most bullets from below should be their own issue to better specify the requirements.

# General
- [x] #21 Create a logical ordering of all the tutorials

# Starting out
- [x] #28 Remove the intro to ros section

# Learning ROS tools
- [ ] #29 Write a short description for all ROS tools used

# Development Tutorials
Development tutorials span multiple packages or deal with new ones.
 
- [ ] #24 Create your own package
- [x] #25 Add a new gait
- [ ] #26 Create your own rqt plugin
- [ ] #31 Create a high level overview
- [x] #47 Travis

# Using the March IV
- [x] #27 Using the gait generator

# Packages

### march_gait_files
- [x] #23 Write package summary

### march_rqt_gait_generator
- [ ] #30 Write package summary

### march_hardware
- [x] #32 Write package summary

### march_hardware_builder
- [x] Write package summary

### march_hardware_interface
- [ ] #33 Write package summary

### march_description
- [ ] #34 Write package summary

### march_gait_scheduler
- [ ] #35 Write package summary

### march_gait_selection
- [ ] #36 Write package summary

### march_launch
- [x] #37 Write package summary

### march_rqt_gait_selection
- [ ] #38 Write package summary

### march_rqt_input_device
- [x] #39 Write package summary

### march_safety
- [x] #40 Write package summary

### march_shared_resources
- [x] #41 Write package summary

### march_sound_scheduler
- [x] #42 Write package summary

### march_tutorials
- [x] #43 Document the documentation

### march_fake_sensor_data
- [x] #44 Write package summary

### (march) input_device
- [x] #48 input device 

### march_simulation
- [x] #45 Write package summary

### march_rqt_launch_menu
- [x] Write package summary

### march_state_machine
- [x] #46 Write package summary
